[package]
name = "roxmltree"
version = "0.15.0"
authors = ["Yevhenii Reizner <razrfalcon@gmail.com>"]
keywords = ["xml", "parser", "tree", "dom"]
categories = ["parser-implementations"]
license = "MIT/Apache-2.0"
description = "Represent an XML as a read-only tree."
repository = "https://github.com/RazrFalcon/roxmltree"
documentation = "https://docs.rs/roxmltree/"
readme = "README.md"
edition = "2018"

[dependencies]
xmlparser = "0.13.3"

[features]
default = ["std"]
std = []
